### ISSUE TITLE
Contacts: Empty password sent if filled in and removed

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#107]
* open the page to add a new contact
* enter the minimum details
* enter anything as password
* remove the password
* Save it
-> error message that the password is invalid. The Frontend sends an emty string as password. If the password field is not touched, no password is sent at all (and the process suceeds)

This also makes the software incompatible with password managers' auto fill features

**Comment by davewood** [comment]
commit d285f82b848c3fe3ca2f42fa1839f07b550afad8
Author: David Schmidt <mail@davidschmidt.at>
Date:   Mon Dec 16 15:05:56 2019 +0100

    dont send empty user.password property


```This also makes the software incompatible with password managers' auto fill features```
How so?

**Comment by certrik** [comment]
@wagner-certat Please comment and close if solved.

**Comment by wagner-certat** [comment]
> "This also makes the software incompatible with password managers' auto fill features"
> How so?

Because the auto-fill features write the credentials into the password field (which is not a login), then the user removes the filled in password manually.

**Comment by wagner-certat** [comment]
On the testing instance, at 7928cfcacfa130a2903e5ccd8d730841d5f08e86 I get an error on clicking the Save button for newly created contacts:

TypeError: "a is undefined"
    o https://cp-aec-tst.cert.at/scripts/scripts.c067fafe.js:1
    x https://cp-aec-tst.cert.at/scripts/scripts.c067fafe.js:1
    i https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    k https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    $digest https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    $apply https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    g https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    r https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    onload https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
 Possibly unhandled rejection: {} vendor.f2ab560e.js:5:25687
    e https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    get https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    j https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    $digest https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    $apply https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:6
    g https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    r https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5
    onload https://cp-aec-tst.cert.at/scripts/vendor.f2ab560e.js:5

And for existing contacts and editing them, same behavior as before.

**Comment by davewood** [comment]
i repeated your steps from the following steps:

- open the page to add a new contact
- enter the minimum details
- enter anything as password
- remove the password
- Save it

this are the request params that were sent:
```
{"user":{"email":"asdf2@asdf2.at","name":"asdfasdf"},"organization_membership":{"membership_role_id":7,"organization_id":9}}
```

no error and I got a notification that the user was added.
