### ISSUE TITLE
User cannot be accessed/deleted after belonging organization is deleted

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#108]
If an orgaization is deleted the users belonging to this organization are not deleted but they cannot be accessed anymore via the web portal. As the login emails are unique you cannot recreate the same users with the same email adress for other orgainzations anymore.
It throws error "Attribute error. Invalid email, phone or mobile?('<duplicate email>', 'duplicate email')"

**Comment by MarkHofstetter** [comment]
all users with no "undeleted" org/membership will be garbage collected

active on tst
