### ISSUE TITLE
Remove "SMS Alerting" button in membership form

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#109]
Remove the "SMS Alerting" button in the membership form as it is not used and implemented in any way.

**Comment by davewood** [comment]
* ca402a8 - (HEAD -> devel, origin/devel) rm sms_alerting from backend (21 seconds ago) <David Schmidt>
* 25cbd2c - rm SMS alerting from frontend (19 minutes ago) <David Schmidt>
