### ISSUE TITLE
New accounts: password sent in plaintext in mails

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#11]
For new accounts an email with the password is sent. Instead, the usual token-based approach should be used.

User gets an email with a link. The page offers to set an initial password.

**Comment by MarkHofstetter** [comment]
ich glaube das entstammt einem Wunsch vom Stefan Lenzhofer, soll ich das in dem Sinne umbauen?

**Comment by MarkHofstetter** [comment]
this works now as follows:
+ if a (admin) user changes the password of a user, the password is changed AND an email with a token is sent:
===
Dear asda asdsad,

just one more step to activate your account. Click on following link to activate it:
http://127.0.0.1:5002/#!/activate-account?token=eyJhbGciOiJIUzI1NiIsImV4cCI6MTUzOTMzNDA2MCwiaWF0IjoxNTM5MzMzMTYwfQ.eyJ1c2VyX2lkIjoxNTh9.gjO1_kGbHLlhpG4Uy7ffTofYZqtkKScOkYbMKptgh18&email=asdasd@asdölku.at

username: asdasd@asdölku.at

====

I'd recommend to leave the possibilty to change the password in place for cases when the users can't access his email 

+ if you change your own password no email is sent

**Comment by MarkHofstetter** [comment]
a few frontend improvements:

+ I've add the email to the url. please add it to the form and make it read-only
+ change the token to read-only as well

+ on error (eg invalid password) stay on page and don't forward to login
+ on success forward to login page

**Comment by certrik** [comment]
https://github.com/certat/do-portal/issues/11#issuecomment-429256021 is not implemented yet.

**Comment by certrik** [comment]
This should be handled differently.
"on error (eg invalid password) stay on page and don't forward to login"

**Comment by davewood** [comment]
done
https://github.com/certat/customer-portal/commit/f5d7402f6e945cf8295a79b9fbec47713a5af15c
https://github.com/certat/customer-portal/commit/6a2249be43bd9711bc2a3245dbe41d126d124584
https://github.com/certat/customer-portal/commit/e9186518efabf67ad2bd959b7953439171001ee9
