### ISSUE TITLE
Send notification email if email address changed

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#112]
User request: If the email address of an login-able user account (org Admins) has been changed, send an e-mail to the old and new address to inform about the change

**Comment by MarkHofstetter** [comment]
please provide Text for the email, I started workiung on the technicalities

**Comment by MarkHofstetter** [comment]
just for clarity: a mail has to be sent if the users (not the memberships) email is changed and the user has a least one one membership with OrgAdmin?

**Comment by MarkHofstetter** [comment]
please test and close
