### ISSUE TITLE
Docker: Please document default (demo) data

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#114]
Please document in the installation documentation for docker, how and which demo data is used: https://github.com/certat/do-portal/blob/master/docs/01_INSTALL.md#docker

**Comment by wagner-certat** [comment]
Please add or link the information to the docker installation documentation

**Comment by MarkHofstetter** [comment]
please check in docs/01_INSTALL.md if this is what you meant

**Comment by wagner-certat** [comment]
Thanks. Applied some syntax and wording fixes in https://github.com/certat/do-portal/commit/00317df83f27625b39f5b9d74f383ec0d3feb31a
