### ISSUE TITLE
Error 500 upon login after with demodata setup

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#117]
A user reported that he had to change line 600 in app/models.py from:

https://github.com/certat/do-portal/blob/532dab952d9e4f09ae99826b0b9138a523fcd613/backend/app/models.py#L600

to

```python
    self._org_ids = [org.organization.id [lookup host] for org in orgs_admins if org.organization ]
```

In order to get rid of error 500 upon login. Setup with docker as documented. Branch master.

Can't try to reproduce at the moment because of #116

**Comment by MarkHofstetter** [comment]
could you please provide the error report from the user?

**Comment by wagner-certat** [comment]
This is the stacktrace which I got:

![screenshot](https://user-images.githubusercontent.com/25031221/78009508-7159cb00-7341-11ea-8930-f721865e44a2.png)

**Comment by MarkHofstetter** [comment]
testing on master - the fix seems rather mysterious to me

**Comment by MarkHofstetter** [comment]
tried and could not reproduce

**Comment by davewood** [comment]
if you try to log in after starting fresh and run `docker-compose up` you get indeed a HTTP 500 response if you try to login with correct credentials.

most likely a CORS issue. im working on it.
