### ISSUE TITLE
Access-Control-Allow-Origin header mismatch

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#12]
# do-portal
laeuft auf port 5001

# customer-portal
laeuft auf port 5002
```
/* ./config/envs/devel.json */
{
  "version": "0.7.0",
  "webServiceUrl": "http://127.0.0.1:5001/cp/1.0",
  "authUrl": "http://127.0.0.1:5001/auth"
}
```

# wenn man nun das login form submitten will
`OPTIONS http://127.0.0.1:5001/auth/login`
## response headers
```
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Allow: POST, OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:5002
access-control-allow-methods: POST, OPTIONS
access-control-max-age: 21600
access-control-allow-credentials: true
access-control-allow-headers: Content-Type, Accept, Authorization, Origin, CP-TOTP-Required
Access-Control-Expose-Headers: Content-Type, Accept, Authorization, Origin, CP-TOTP-Required
Content-Length: 0
Server: Werkzeug/0.11.15 Python/3.5.3
Date: Mon, 13 Aug 2018 09:58:36 GMT
```

app zeigt nur `ajax error` als notification an weil das exception object so aussieht:
`Object { data: null, status: -1, headers: headersGetter/<(), config: Object, statusText: "", xhrStatus: "error" }`

das kommt von hier:
```
/* app/scripts/services/auth.js */
      login: function (credentials) {
        return $http.post(config.apiConfig.authUrl + '/login', credentials)
          .then(cacheSession);
      },
```

prinzipiell ist das eine fehlkonfiguration zwischen do-portal und customer-portal die nicht ganz trivial zu finden ist.

**Comment by wagner-certat** [comment]
Is this fixed in the code or was this a misconfiguration of the setups?

**Comment by davewood** [comment]
misconfiguration of the setups

**Comment by wagner-certat** [comment]
Is it documented how to do it correctly?

**Comment by davewood** [comment]
well, you have to tell the frontend app where the API runs, dont know if that really needs documentation.
