### ISSUE TITLE
organizations not displayed correctly

### ISSUE THREAD

**Issue by MarkHofstetter** [certat/do-portal#124]
if  a contact is org admin of two different orgs on two completely different branches in the org tree only the organisation (branch) of the last added membership is shown see test 

 tests/test_alias_user.py

this rather severe and needs to be fixed for #97

**Comment by MarkHofstetter** [comment]
fixed in ee1a8a24908995fd42be411736706e2e5526c556

**Comment by wagner-certat** [comment]
Could this be related to #91 and #99 ?

**Comment by MarkHofstetter** [comment]
rather not, this is the other way round
