### ISSUE TITLE
Backend always return 403

### ISSUE THREAD

**Issue by vetsolution** [certat/do-portal#125]
Hello,

After the installation of do-portal with docker, once I'm connected with master@master.master account, I can't list any organization, or other tabs , and when I look into the developer tools I notice that all api call to the backend fail with 403 error.
Do you think is a configuration error or an error in the request?
This is a screen of the request, should it be an authentication header, or is it managed by the cookies?
![Screenshot from 2020-04-20 15-57-36](https://user-images.githubusercontent.com/11541798/79766528-61be1880-8328-11ea-9179-dc0641b435f0.png)

**Comment by davewood** [comment]
the correct URL is *portal-frontend:8081*

portal-backend:8081 is deprecated and will be removed.

**Comment by vetsolution** [comment]
Hello,
Thank for the info.
But in the frontend I cannot add any organisation because I don't have any parent organisation
![image](https://user-images.githubusercontent.com/11541798/79965675-9c40c600-848c-11ea-967a-512c9151266c.png)

Moreover, I cannot specify any ASN, FQDNs,IP Ranges,... as in backend.

I have an another question, where is the EventDb infos I dont see any tabs about it ?

Thank you for your help ;)
