### ISSUE TITLE
RE: Backend always return 403 

### ISSUE THREAD

**Issue by vetsolution** [certat/do-portal#126]
Hello
Sorry for opening a new issue but it seem that reply to a closed issue don't send notification.
So I repost it here
Regards,

---------------------------------

Hello,
Thank for the info.
But in the frontend I cannot add any organisation because I don't have any parent organisation
![image](https://user-images.githubusercontent.com/11541798/79965675-9c40c600-848c-11ea-967a-512c9151266c.png)

Moreover, I cannot specify any ASN, FQDNs,IP Ranges,... as in backend.

I have an another question, where is the EventDb infos I dont see any tabs about it ?

Thank you for your help ;)

_Originally posted by @vetsolution in https://github.com/certat/do-portal/issues/125#issuecomment-617667734_

**Comment by MarkHofstetter** [comment]
**no problem on opening issues and asking questions, you are very welcome!** 

1. create organizations and users:

you have to "bootstrap" the database to make the portal usable

so either create an organisation manually via SQL in the database with your user as the OrgAdmin

or BETTER see 
python3 demodata.py addyaml
demodata.py:def addyaml():
app/fixtures/testfixture.py:   def addyaml(yamlfile = "install/testdata.yaml"):

you may either edit the provided yamlfiles (eg master_user.yaml)  or create a new one and call the addyaml function

2. the basic idea for ASN, FQDNs,IP Ranges,... is not to create them manually, we fetch them from the ripe database and import them in a separate schema (fody) in the database

**Comment by wagner-certat** [comment]
> or BETTER see
> python3 demodata.py addyaml
> demodata.py:def addyaml():
> app/fixtures/testfixture.py: def addyaml(yamlfile = "install/testdata.yaml"):
> 
> you may either edit the provided yamlfiles (eg master_user.yaml) or create a new one and call the addyaml function
Can you please add to the [installation documentation](https://github.com/certat/do-portal/blob/master/docs/01_INSTALL.md#install) that the yaml file should be newly created / adapted? Thanks

**Comment by vetsolution** [comment]
I think the data was already imported.
I found the problem, in organisation_membership, the account master@master.master wasn't linked to any organisation.

Another questions:
What should I fill in Ripe handle field ?
![image](https://user-images.githubusercontent.com/11541798/80590233-daedf780-8a1b-11ea-9b4d-424802762fcc.png)

Also I dont see any event tabs nor table in db, I though that fody handle event and do-portal include fody, am I wrong ?

Many thanks

**Comment by wagner-certat** [comment]
> Another questions:
> What should I fill in Ripe handle field ?
The organisation handle (`ORG-*-RIPE`)

> Also I dont see any event tabs nor table in db, I though that fody handle event and do-portal include fody, am I wrong ?
No, fody is not "included" in do-portal. _Strictly_ speaking it is not related, as the RIPE import is not part of fody, but part of the certbund-contact-expert. As we do not re-invent the wheel here, there's no query interface for IntelMQ events table included in do-portal, fody's events/statistics component is doing a good job for that.

**Comment by vetsolution** [comment]
So I should install fody for event handling, then do-portal for contact management ?

**Comment by wagner-certat** [comment]
> So I should install fody for event handling

What do you mean by event handling?

**Comment by vetsolution** [comment]
Assign event to a customer (I suppose it's done with DO Portal Expert Bot).
Then let customer acces to their event
And optional functionality: mark an event as "done"

**Comment by wagner-certat** [comment]
> Assign event to a customer (I suppose it's done with DO Portal Expert Bot).
> Then let customer acces to their event
> And optional functionality: mark an event as "done"

That's neither currently possible nor in scope of future developments, sorry.

**Comment by wagner-certat** [comment]
@vetsolution This software is now in maintenance mode, more information here: https://github.com/certat/do-portal/issues/133
