### ISSUE TITLE
Docker container gives error 503

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#129]
Branch devel, commit a179eece08c9b2f25e164d4847083f39451e1a73
http://127.0.0.1:8081/ gives:

> 503 Service Temporarily Unavailable
> nginx/1.17.6

[Complete output](https://github.com/certat/do-portal/files/4774255/docker.log) of `docker-compose up`.

**Comment by MarkHofstetter** [comment]
"have you tried turning it on and off?"

seriously please try composer down and composer up again. Did Docker work on this system before?

**Comment by wagner-certat** [comment]
> seriously please try composer down and composer up again.

Do you mean `docker-compose` instead of `compose`?

[Output of docker-compose down](https://github.com/certat/do-portal/files/4778629/docker-down.log)
[Output of docker-compose up](https://github.com/certat/do-portal/files/4778631/docker-up.log)

> Did Docker work on this system before?

How can I test that?

**Comment by davewood** [comment]
- remove all running docker containers `docker-compose down`
- remove all docker images `docker image ls` should not list any doportal related images
- remove all docker volumes `docker volume ls` should not list any doportal related volumes
- remove/move the doportal directory `mv do-portal do-portal.bak`
- checkout the repository again `git clone ...`
- build the images
- start the containers again.

if this doesnt work then something is wrong and I will look into it.

**Comment by wagner-certat** [comment]
>     * remove/move the doportal directory `mv do-portal do-portal.bak`
> 
>     * checkout the repository again `git clone ...`

May I ask what for?

**Comment by davewood** [comment]
just to make sure we start with a clean slate. if everything works with your approach you can omit the commands.

**Comment by wagner-certat** [comment]
Now I got this error on the console:
```
portal-backend          | FileNotFoundError: [Errno 2] No such file or directory: '/home/sebastianw/dev/do-portal/backend/logs/audit.log'
```
[Complete log](https://github.com/certat/do-portal/files/4779725/clean-docker-compose-up.log)

Upon a second `docker-compose up` I again get a 503, like before.

[Complete log](https://github.com/certat/do-portal/files/4779749/docker-compose-up.log)

**Comment by davewood** [comment]
there has been a frontend issue that I just resolved. and there seems to be another backend issue that we will take care of. tbc

**Comment by MarkHofstetter** [comment]
tried hard to reproduce - couldnt. Probably have to resolve this together

**Comment by davewood** [comment]
```
cd do-portal
docker-compose down
cd ..
mv do-portal do-portal.bak
git clone https://github.com/certat/do-portal.git
cp do-portal.bak/frontend/secret.json do-portal/frontend/
cd do-portal
docker volume rm do-portal_portal_db_data
docker image rm do-portal_portal-backend:latest
docker image rm do-portal_portal-frontend:latest
git checkout devel
docker-compose up
```

the master@master.master user that is created in the docker environment is broken somehow, mark is looking into it.

**Comment by MarkHofstetter** [comment]
whoever wrote install/master_user.yaml
(did this ever work?)

in the user part of the yaml file the abbreviation has to be used to specify the org
