### ISSUE TITLE
Update process has to work and to be documented

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#14]
After software or database changes the update process has to work. 
Also the process of how to update has to be documented.

**Comment by davewood** [comment]
requires the OS version and desired software versions.

then we can setup a clean virtualbox and play through the installation process and document it along the way.

**Comment by certrik** [comment]
OS version is Debian 8 or 9 (would be interesting if there is a difference. There shouldn't be one).
The version as of now. The update process should work regardless of the version.

**Comment by wagner-certat** [comment]
Currently we are using 8, but we want to migrate to 9. It this is not possible it's a bug (which can be discussed separately).

So I think that creating the docs for Debian 9 would reveal possible issues.

I remember there were issues with Debian 9 around a year ago.

**Comment by davewood** [comment]
closed https://github.com/certat/do-portal/issues/23

**Comment by certrik** [comment]
will be upgrading production system soon. Any special advise? UPGRADE process is not completely clear.
