### ISSUE TITLE
Role management/view problem

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#15]
Roles that are deleted still are viewed in the contact details.
If the role is added again, it is shown twice (trice) in the contact details and cannot be deleted (Error: Resource not found) or edited (Error: `<html><head><title>502 Bad Gateway</title></head> <body bgcolor="white"><center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.6.2</center></body></html>` ). The original role can be deleted but is still shown in the contact details but not in the organizational details (but only after logging out and in again).

**Comment by davewood** [comment]
reproduction steps:

1) create new contact (in fact user)
2) login with new user credentials
3) select organisation
4) add new contact+membership
5) add another membership
6) delete second membership -> backend returns success msg
7) reload page
8) membership is still displayed
8) try delete again -> Resource not found

**Comment by davewood** [comment]
aha, membership is als deleted in der DB markiert. sollt wohl die API dann nimmer verlassen.
