### ISSUE TITLE
Error thrown but access still granted

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#16]
As role "Adminstrator Organisation" of an organization the error: "You don't have the permissions to access the requested resource. It is either read-protected or not readable by the server." is thrown. It is still rightfully possible to edited the organizational contacts and structures.
I assume that the error is thrown because the query somehow tries to access a resource from the parent of this organization which is not granted.

**Comment by wagner-certat** [comment]
error is shown on https://cp-aec-stg.cert.at/#!/organizations/<id\> where ID is the ID of the own organization

**Comment by davewood** [comment]
commit b3d1dc9e071179253d844597b18584c49ff36975
    fix: dont query/show parent org
