### ISSUE TITLE
Bug: all users can see all organizations

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#17]
After the recent performance increases, a user can call
/#!/organizations/<other org id> and
/api/1.0/organizations/<other org id>
if the user is not allowed to do so. Previously to the changes the requests were correctly denied with 403.

**Comment by MarkHofstetter** [comment]
what does this exactly mean? are datasets returned the logged in user is not allowed to access?
please provide more details:
+which user?
+(which route - is provided)
+ what is returned
+ what should be returned

**Comment by MarkHofstetter** [comment]
fixed in f1865559fe91d2335675581433ad5cd75aa8d975
