### ISSUE TITLE
Performance issue with priviliged user

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#19]
Requesting contacts (#!/user_list) needs 327 queries and 7 seconds to load. This is too many/ too long.

**Comment by MarkHofstetter** [comment]
please (always) report:
+ on which installation did the bug occur
+ which branch/commit

**Comment by certrik** [comment]
The bug occurs on the staging system with status 58a43dca9328d1fb195a67aa58a9270aa5f5d16a on the frontend and 700565fc48a44cd7ece0c8b0e92f164cd777e787 on the backend.

**Comment by davewood** [comment]
auf unsrer stg maschine.

backend: branch release,  commit 700565fc48a44cd7ece0c8b0e92f164cd777e787
frontend is auf stand

**Comment by wagner-certat** [comment]
Just re-tested: Backend is at 700565fc48a44cd7ece0c8b0e92f164cd777e787 and the loading the user list takes 7 seconds

**Comment by MarkHofstetter** [comment]
ok, found the problem. A lot of unneeded legacy tables are too eagerly loaded, removing and or mitigating the problem

**Comment by wagner-certat** [comment]
backend is at 7b5d7a6fb1f3256c4f43bd7d9d4fbe844952104d, nginx and uwsgi restarted and loading user list takes 18s.

**Comment by wagner-certat** [comment]
Heute sinds noch mehr: 35s
Wieder mit 7b5d7a6fb1f3256c4f43bd7d9d4fbe844952104d

![do-portal-screenshot_2018-09-11_09-39-55](https://user-images.githubusercontent.com/25031221/45345476-b7580e00-b5a6-11e8-9771-9f6e3a5844d5.png)

**Comment by MarkHofstetter** [comment]
ja ich bin schon am schauen, dass ganze ist sicher nicht optimal, aber ich denke, dass da auch die Kiste was hat/dazu beiträgt. 

ich schau gradem bitte nix angreifen

**Comment by davewood** [comment]
@wagner-certat das hat mit dem code glaub ich weniger zu tun sondern is entweder ein concurrency issue oder bloat. nachdem ich mich neu einloggen hab muessen vermute ich jemand hat die kiste neu gestartet (bzw services) und nun sinds wieder 7-8s

**Comment by aaronkaplan** [comment]
Wie viel?

---
Mobile

**Comment by MarkHofstetter** [comment]
gut der Speicher wars nicht (aber auch nicht schlecht), man muß dem SQLAlchemy aktiv sagen, dass es gewisse Spalten nicht laden so, jetzt flutscht es

**Comment by wagner-certat** [comment]
Mit 9fb10623056498b90063c99481a090b4890a0273 sind es nun 17s
![do-portal-screenshot_2018-09-11_11-09-51](https://user-images.githubusercontent.com/25031221/45350065-3ce1bb00-b5b3-11e8-9aa3-b2bf861795f8.png)

**Comment by wagner-certat** [comment]
Es sind nun fuer users 400 ms, organization_memberships 500ms und fuer organizations 500ms
Ich hab nun 42 Queries fuer die user list gezaehlt

Bei organizations sinds fast 300ms und 11 queries

**Comment by wagner-certat** [comment]
Ich hab das "flutschen" quantifiziert.

Fuer einen un-/wenig privilegierten User (eine suborg, 2 kontakte) sind es fast 300ms bei den organizations bei 11 Queries und mehr als 400ms fuer die user bei 40 Queries.

> imho passt das jetzt, oder?

-> @certrik

**Comment by MarkHofstetter** [comment]
ja muß man sich überlegen wieviele Streicheleinheiten man da noch reinstecken will. 

von der performance her ist es mal ausreichend, die Zahl der queries schreckt mich auch nicht wirklich, wiewohl man da sicher weiter runterkommen könnte wenn man es wissen wollte

**Comment by certrik** [comment]
Geschwindigkeit passt. Danke vielmals. 
Da diese Woche aber noch im Zeichen der Performance steht, könnte man natürlich noch etwas nachforschen, ob es nicht noch schneller geht.

**Comment by MarkHofstetter** [comment]
ich denke am sinnvollsten ist wenn wir diese Woche noch was machen wollen, dass wir schön langsam an paging denken. das bringt mehr

**Comment by certrik** [comment]
Macht aber erst Sinn, wenn wir eine Suche oder ähnliches haben. Neue Features sind aber vorerst mal nicht im Fokus.

**Comment by MarkHofstetter** [comment]
closing to avoid confusion, if new issues occur please open new bug
