### ISSUE TITLE
Add "find as you type" search for export UI

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#22]
Add "find as you type" fields at the top of each column in /#!/user_export .

**Comment by certrik** [comment]
if it is not an "overkill" to implement it, then please proceed.

**Comment by davewood** [comment]
angularjs und datatables moegen sich nicht so recht

https://www.datatables.net/forums/discussion/21286/datatables-and-angularjs


werd mir daher http://ui-grid.info anschaun

**Comment by davewood** [comment]
allerdings hat das 337K ... bower_components/angular-ui-grid/ui-grid.min.js

bitte entscheiden ob wir das wollen. funktioniert tuts und erfuellt die anforderungen an filtern, sortieren und hoffentlich auch csv export

**Comment by certrik** [comment]
As discussed ... please strip it as much as possible and then you are good to go.

**Comment by davewood** [comment]
progress can be reviewd in branch topic-uigrid

**Comment by davewood** [comment]
find as you type implemented and working in branch topic-uigrid
