### ISSUE TITLE
Setup Instructions (docker)

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#23]
both repos (do+ cp) now have a topic-docker branch.

https://github.com/certat/do-portal/blob/topic-docker/docs/docker.md

for a non-docker setup follow the instructions in the respective Dockerfiles

https://github.com/certat/do-portal/blob/topic-docker/Dockerfile
https://github.com/certat/customer-portal/blob/topic-docker/Dockerfile

**Comment by certrik** [comment]
Now we need instructions for Debian (9) without Docker.
