### ISSUE TITLE
allow upper case chars for users' email addresses

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#26]
It seems that for users only lower case email addresses are allowed, which is not intuitive as email addresses are (according to RFC) case sensitive and in practice used case-insensitive. For memberships, upper case characters *are* allowed.

So I propose to allow upper case characters for users' email addresses too.

**Comment by MarkHofstetter** [comment]
fixed in 41e5d9df20fdd420771b8debcf64a500474dd79f
