### ISSUE TITLE
Display parent organization

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#28]
In the organization view the parent organization's name should be displayed.

**Comment by davewood** [comment]
cp-portal: commit 4bfed828657906bd3bc78c422cdc8cc8cac48b6d

do-portal needs to serve org.parent_org_abbreviation for /organizations/:id

**Comment by MarkHofstetter** [comment]
implemented in 41e97686acf430a0c8c39cd0305a010d0a3a8742
