### ISSUE TITLE
runtime log warning

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#33]
do-portal    | ERROR in mixins [/home/cert/do-portal/app/utils/mixins.py:39]:
do-portal    | 'NoneType' object has no attribute 'abbreviation'

think that came up the first time when we started displaying parent_org_name

**Comment by davewood** [comment]
https://github.com/certat/do-portal/issues/42

**Comment by MarkHofstetter** [comment]
I guess this is fixed as the error does not occur any more
