### ISSUE TITLE
password reset email body

### ISSUE THREAD

**Issue by MarkHofstetter** [certat/do-portal#36]
Betreff ist im Moment "reset password".
Soll lauten "Austrian Energy CERT - Kontaktdatenbank:
Account-Aktivierung/Passwort-Reset"

Text soll Deutsch und Englisch sein:
"
Lieber <User>,

nur mehr ein weiterer Schritt um dein initiales Passwort festzulegen
oder dein altes neu zu setzen.
Klicke auf folgenden Link:
https://<domain>/auth/activate-account/eyJleHAiOjE1Mzk2MDE3NjksImFsZyI6IkhTMjU2IiwiaWF0IjoxNTM5NjAwODY5fQ.eyJ1c2VyX2lkIjo0MjJ9.Zb9ruNfDCItYEwr0qHoOxtxzSX0BNLgq5qBhJvaOvYU

Dear <User>,

only one more step to set your initial password or reset your old one.
Click on following link:
https://<domain>/auth/activate-account/eyJleHAiOjE1Mzk2MDE3NjksImFsZyI6IkhTMjU2IiwiaWF0IjoxNTM5NjAwODY5fQ.eyJ1c2VyX2lkIjo0MjJ9.Zb9ruNfDCItYEwr0qHoOxtxzSX0BNLgq5qBhJvaOvYU

-- 
// Austrian Energy CERT - https://www.energy-cert.at/
// T: +43 1 505 6416 92
// E: team[at]energy-cert.at (edited for anti-spam issues [at] should be @ of course)
// Eine Initiative der österreichischen
// Elektrizitäts- und Erdgaswirtschaft und
// nic.at GmbH, Firmenbuchnummer 172568b, LG Salzburg

**Comment by MarkHofstetter** [comment]
done 

I suggest considering adding
+ the username (=email address) 
+ an informative url 
+ a separator between the german and english text

**Comment by wagner-certat** [comment]
Ad informative URL:

Unfortunately there are no pages that could be linked :/

**Comment by certrik** [comment]
an informative url is not needed at the moment.

**Comment by MarkHofstetter** [comment]
my suggestion was misleading, I meant the login name which is only shown in the url at the moment

**Comment by certrik** [comment]
Well okay. Lets do it that way:
"
Lieber ,

Dein Benutzername ist <email> . Nur mehr ein weiterer Schritt um dein initiales Passwort festzulegen
oder dein altes neu zu setzen.
Bitte klicke auf den folgenden Link:
https:///auth/activate-account/eyJleHAiOjE1Mzk2MDE3NjksImFsZyI6IkhTMjU2IiwiaWF0IjoxNTM5NjAwODY5fQ.eyJ1c2VyX2lkIjo0MjJ9.Zb9ruNfDCItYEwr0qHoOxtxzSX0BNLgq5qBhJvaOvYU

Dein Austrian Energy CERT - https://www.energy-cert.at/
--------------------------------

Dear ,

Your username is <email>. Only one more step to set your initial password or reset your old one.
Please click on following link:
https:///auth/activate-account/eyJleHAiOjE1Mzk2MDE3NjksImFsZyI6IkhTMjU2IiwiaWF0IjoxNTM5NjAwODY5fQ.eyJ1c2VyX2lkIjo0MjJ9.Zb9ruNfDCItYEwr0qHoOxtxzSX0BNLgq5qBhJvaOvYU

Your Austrian Energy CERT - https://www.energy-cert.at/
---------------------------------

--
// Austrian Energy CERT - https://www.energy-cert.at/
// T: +43 1 505 6416 92
// E: team[at]energy-cert.at (edited for anti-spam issues [at] should be @ of course)
// Eine Initiative der österreichischen
// Elektrizitäts- und Erdgaswirtschaft und
// nic.at GmbH, Firmenbuchnummer 172568b, LG Salzburg
"

**Comment by certrik** [comment]
Make the site /#!/activate-account?token= redirect the now logged in user to the main page /#!/organization_list .
Also please remove the small text "activate account" from the site /#!/activate-account?token= .

**Comment by MarkHofstetter** [comment]
done & relaesed

**Comment by certrik** [comment]
Please review the text again. It is not the exact text from https://github.com/certat/do-portal/issues/36#issuecomment-430531065 . Also please don't remove the email adress. It is just [at] here in the comments.

**Comment by certrik** [comment]
Please reviwe github comments again. Also sent you mail.
