### ISSUE TITLE
Link RIPE-orgas to do-orgas via RIPE-handle 

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#37]
Link RIPE-orgas to do-orgas via RIPE-handle following the principle described in https://github.com/certat/do-portal/wiki/fody-implementation#data-structure .

**Comment by davewood** [comment]
https://github.com/certat/do-portal/wiki/Fody-API-Endpoints

ich hoff wenn das ripe-handle nicht existiert kommt nicht nur die message sondern auch ein HTTP 404
