### ISSUE TITLE
Notification shows raw JSON

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#40]
Editing an organizations' details gives the shown message.
![customer-portal-screenshot_2018-10-29_17-30-43](https://user-images.githubusercontent.com/25031221/47665263-fc5cf180-dba0-11e8-9572-a8c239951175.png)

**Comment by davewood** [comment]
fixed: https://github.com/certat/customer-portal/commit/1dcf05e866d51c844050aa93a3b27fd3cdc34728

**Comment by wagner-certat** [comment]
deployed, works
