### ISSUE TITLE
Variable error 502 when accessing orgs or contacts

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#41]
There are variable error 502 when accessing /#!/organization_list or /#!/user_list. See screenshot ...
![grafik](https://user-images.githubusercontent.com/42176839/47705293-68ce0400-dc26-11e8-9a0e-a8066e3877af.png)

**Comment by MarkHofstetter** [comment]
Model instances gets detached from db session - must investigate, restart of uwsgi service is a temporary "fix"

**Comment by wagner-certat** [comment]
Did not happen anymore in the last hour
