### ISSUE TITLE
Add possibility to jump back from user to belonging organization

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#48]
If editing a user, for example /#!/users/14, it would be good to be able to jump back to the belonging organization. Not sure about the best way to do it yet. But would improve useability.

**Comment by davewood** [comment]
so display a link to the organization of each membership on user edit page? (e.g.:  /#!/users/14)

**Comment by certrik** [comment]
Yes, something like that.

**Comment by davewood** [comment]
How about including said link in #!/user_list?
Feels like the proper place to me.

**Comment by certrik** [comment]
No, e.g.  /#!/users/14 is the right place. Because if you are editing the user, it is practical to be able to jump back to the belonging orga.
But to be able to jump to the orga from #!/user_list would be practical too.

**Comment by davewood** [comment]
done

* 7e72c13 - add link to orga on user edit page (25 hours ago) <David Schmidt>
* 63ce71c - add link to orga on user list page (26 hours ago) <David Schmidt>

**Comment by certrik** [comment]
In for example /#!/users/158 or /#!/users/10 the link is correct but the roles are not correct. Sometime also the role is blank "()".

**Comment by davewood** [comment]
* 9d693b2 - (HEAD -> devel, origin/devel) fix roles/organizations mapping (18 seconds ago) <David Schmidt>
