### ISSUE TITLE
Cannot add contacts to newly created organisation

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#50]
If a new organisation is created it of course hasnt any members. But therefore the field "Memberships" is not displayed making it not possible to add contacts from the Cannot add contacts to newly created organisation view e.g. /#!/organizations/5072 .
Even if there is no contact/membership in an organisation the field "Memberships" should be displayed nevertheless.

**Comment by davewood** [comment]
* 0d23b86 - (HEAD -> devel, origin/devel) fix: show "new contact" button (13 seconds ago) <David Schmidt>

**Comment by wagner-certat** [comment]
works
