### ISSUE TITLE
If abuse-c is set manually it should be set as main abuse-c and indicated

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#54]
If the Abuse-C contact is set manually it has priority over the Abuse-C automatic from RipeDB. This should also be indicated in the frontend somehow.

**Comment by certrik** [comment]
1. Yes the return result when the settings are queried.
2. True. This should not be possible. It should be prevented to add another manual abuse-c.

**Comment by certrik** [comment]
Cannot test beacuse adding ripe handle throws 502 error.
![error_ripe](https://user-images.githubusercontent.com/42176839/51478063-a7d5a680-1d8a-11e9-8e27-74099de54119.jpg)

**Comment by certrik** [comment]
Nope. Doesnt work.

**Comment by MarkHofstetter** [comment]
please some details which handle does not work on which organisation etc

**Comment by MarkHofstetter** [comment]
just checked it locally (can't connect to webserver via vpn) and everything works as expected

**Comment by certrik** [comment]
Tried to reuse an already existing ripe handle and the correct error "his RIPE handle already exists. " is thrown. So it seems like a different problem.

**Comment by MarkHofstetter** [comment]
I am able to reproduce the error now, have to check/fix on stage beacuse cannot reproduce on my devel machine

**Comment by MarkHofstetter** [comment]
works now, a db migration was missing

**Comment by MarkHofstetter** [comment]
please try again, detached session problems (hopefuly) resolved

**Comment by certrik** [comment]
Abuse-C is not shown. ORG-ESTG1-RIPE

**Comment by MarkHofstetter** [comment]
i just added ORG-ESTG1-RIPE to 
Parent Organization: Organization Abbreviation 4
Name: Organization Full Name 20
Abbreviation: Organization Abbreviation 20

https://cp-aec-stg.cert.at/#!/organizations/20

and it worked w/o problems

**Comment by certrik** [comment]
Well adding the ripe-handle works. That is true but I don't see the abuse-c contact.

**Comment by MarkHofstetter** [comment]
abusec is returned but not displayed 

{"abusec": ["f"], "asns": [{"asn": "21039", "notification_setting": {}}], "cidrs": [{"cidr": "2a0a:1e00::/29", "notification_setting": {}}, {"cidr": "193.186.224.0/20", "notification_setting": {}}, {"cidr": "193.186.240.0/21", "notification_setting": {}}, {"cidr": "193.186.216.0/21", "notification_setting": {}}], "name": ""}

**Comment by davewood** [comment]
ripe abusecs used to be delivered as 
> {"abusecs": ...}
now they come as 
> {"abusec": ...}

**Comment by davewood** [comment]
since the value of abuse[c] is an array the old form (abusecs) makes more sense to me.

**Comment by MarkHofstetter** [comment]
it's abusec (again)

**Comment by davewood** [comment]
works on stg again now.

**Comment by certrik** [comment]
Can confirm that abuse-c is shown again. Thanks. 
But still there is no indication that it is not used anymore if a manual abuse-c is provided. 
> 
> If an automatic abuse-c is deactivated by defining at least one manual abuse-c than the automatic abuse-c should be greyed out and the comment field should state "DEACTIVATED manually"

**Comment by MarkHofstetter** [comment]
what do you mean by 

> But still there is no indication that it is not used anymore if a manual abuse-c is provided.

the web does not use it anyway, and the API call either gets the ripe abusec OR the manual abusec if present

It may be useful to have some clear documentation that for OUR automatic services the manual abusec has precedence

**Comment by certrik** [comment]
It should be clearly visible by the user of the frontend that the manual abuse-c is prefered. Just usability improvement.

**Comment by davewood** [comment]
Is it sufficient if "Abuse-C Automatic" email addresses are greyed out? (see stageing env for an example)

**Comment by certrik** [comment]
Well it would be better if it is also stated in the comment. Is it somehow possible to implement that or would it break a lot. I am just looking for a good way that the user who possibly doesnt know anything sees at first sight what is going on.

**Comment by davewood** [comment]
what change to the current state would you like to see in the comment?

**Comment by certrik** [comment]
If possible change the comment to "DEACTIVATED manually" .

**Comment by certrik** [comment]
It seems not to work. Just tested on staging. Organization 20. Abuse-C automatic email address is shown grey. It stays grey even if manual abuse-c is delted. Comment section of abuse-c automatic is not altered in any way.

**Comment by davewood** [comment]
it doesn now after git pull

**Comment by certrik** [comment]
Thanks
