### ISSUE TITLE
Expose API key on /#!/account

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#58]
The API key should be exposed in the account settings page /#!/account .

**Comment by wagner-certat** [comment]
By default no key is set, should it be generated automatically, or on demand? If the latter, can it be re-generated?

**Comment by MarkHofstetter** [comment]
furthermore: is every user allowed to have/use an api key or maybe only certain (new) roles

**Comment by certrik** [comment]
It should be generated automatically at the moment.
All users with the role "Administrator Organisation" should be shown the API key.

**Comment by MarkHofstetter** [comment]
an api key ist now created for users with commit
4f8683c669d8b6b6203c0c98fc3f9238215f0f0c

**Comment by davewood** [comment]
if backend sends an api key it is now shown

**Comment by MarkHofstetter** [comment]
api key is shown
