### ISSUE TITLE
paging

### ISSUE THREAD

**Issue by MarkHofstetter** [certat/do-portal#62]
paging infrastructure

**Comment by davewood** [comment]
lazy loading tree viewer in JS https://github.com/davewood/treejo

**Comment by MarkHofstetter** [comment]
Überlegungen Paging Organisationen:

ich hab mich gestern und heute mit der paging Problematik f. Organisationen beschäftigt

+ erste Idee: einfach einen Treeviewer zu machen, dh man zeigt immer eine Ebene an und kann dann per click tiefer graben

leider wird das vermutlich das Problem bei uns nicht lösen, nachdem wir wahrscheinlich keine schönen Baum haben werden, sondern sich das allermeiste direkt unter dem admin abspielen wird

+ zweite Idee: wenn ein Resultat mehr als x (zb 1000) Zeilen resultieren würde, "zwingen" wir den User zur eingabe eines Suchfilters, und erst dann wird dann das Resultat mit dem reduzierten Baum angezeigt

+ dritte Idee (die mir am wenigsten gefällt): wir flatten das Resultat, dh

aus

A

    B

        D

         E

    C

würde

A => B

A => B => D

A => B => E

A => C

und dass könnten wir dann vernünftig pagen

**Comment by certrik** [comment]
As briefly discussed ...
Please implement as standard paging solution. Means one page is shown at a time with a link to get to next page and vice versa. The content is rendered alphabetically per subtree.
Please also reduce data which is transfered to the minimum needed for showing the content.

**Comment by MarkHofstetter** [comment]
optimized loading time by a factor of 10, and put paging infrastructure in place (not used yet), should be ok now

**Comment by davewood** [comment]
TODO: check if frontend javascript code can be simplified now

**Comment by davewood** [comment]
frontend code takes care of parent-child relationship. cannot be simplified without re-implementing same code in backend. im leaving code as is.
