### ISSUE TITLE
Strange behaviour after idle time

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#64]
![logout_behaviour](https://user-images.githubusercontent.com/42176839/51042829-8c65e100-15bd-11e9-87a1-07eae2564001.jpg)
After being idle for aprox. 15 minutes at /#!/user_list and going back to /#!/organization_list the list of organizations is shown. Trying to go to /#!/account error unauthorized is thrown and you are at the login page. I assume that goinig to any other page different from /#!/account would have thrown same error and results.

**Comment by davewood** [comment]
session timeout probably.

**Comment by davewood** [comment]
same happened to me.

currently set to 30 minutes in config.py

`PERMANENT_SESSION_LIFETIME = timedelta(minutes=30)`

do you want a specific timeout?

**Comment by davewood** [comment]
did you click the back button of your browser or click the 'Organizations' link?

**Comment by MarkHofstetter** [comment]
session timeout handling is implemented rather strange at the moment, some improvement have to be done there anyway

**Comment by certrik** [comment]
I have clicked the  'Organizations' link.

**Comment by davewood** [comment]
im testing the displaying of the organizations list after the session timed out, i guess its just a cached view.

**Comment by davewood** [comment]
doesnt seem to be a cache issue.

**Comment by MarkHofstetter** [comment]
could not reproduce locally, going to diff configs

**Comment by davewood** [comment]
on my local installation im not logged out after 30 minutes either.

**Comment by certrik** [comment]
Any new information regarding this issue?

**Comment by davewood** [comment]
i tried again on our staging env, waited 18 minutes and nothing of importance happend. no timeout, no error, no warning, it just kept working.

**Comment by MarkHofstetter** [comment]
I was twice as diligent as David and waited 36 minutes for nothing to happen

**Comment by aldot** [comment]
Wie hieß es bei der OE3 Rechtschreibreform so schön? "Wer geht mit was trinken"

**Comment by davewood** [comment]
left my computer running and the page open in my browser, clicked the organizations link and the login page appeared.

**Comment by davewood** [comment]
so far the behaviour (as observed by Mark and I) is as expected. If you still experience the bug please check whats actually happening. especially which requests are sent and the responses are of significance.

**Comment by certrik** [comment]
![image](https://user-images.githubusercontent.com/42176839/57302631-ee51d580-70db-11e9-89e9-b32b4f7b3fa4.png)
There are aproximately two hours between the actions in the green box. The actions in the blue box are done within a minute. 
What can you see. I log in. Click on an organisation. Wait two hours. Click on link "Organizations" to /#!/organization_list . The page is loaded. Try to click an other organisation in the list. Redirected to login page.
Why is /#!/organization_list still loaded after two hours of login and I am not directly redirected to the login page as my login has apparently timed out.

**Comment by wagner-certat** [comment]
I see the same behavior somtimes btw
