### ISSUE TITLE
create vs update user, different validation

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#65]
creating a user requires membership data to be filled out.

you can omit phone, email, address and submit and no warning is shown.

if you edit the same user now and just click save on the same membership you get an error saying

>  Attribute error. Invalid email, phone or mobile? 

which membership attributes are required and which are optional?

**Comment by davewood** [comment]
better explanation: membership-create doesnt validate/require phone/addr/email but membership-update does.

**Comment by certrik** [comment]
It should not be required to add a phone number or email in membership roles. But if it is provided it should be validated. 
At least for most roles. Is there a possibility to define certain membership roles that need an email or phone or both?

**Comment by MarkHofstetter** [comment]
actually there if there is a role sms_alerting which require a mobile number

**Comment by certrik** [comment]
That is what I meant.
But please fix ...
> 
> 
> better explanation: membership-create doesnt validate/require phone/addr/email but membership-update does.

**Comment by MarkHofstetter** [comment]
fixed
