### ISSUE TITLE
RIPE/fody DB schema documentation

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#66]
the ripe db dump requires already existing structures, where do they come from?

```
cert_db      | ERROR:  relation "public.autonomous_system_annotation" does not exist
cert_db      | STATEMENT:  ALTER SEQUENCE fody.autonomous_system_annotation_autonomous_system_annotation_i_seq OWNED BY public.autonomous_system_annotation.autonomous_system_annotation_id;
do-portal    | psql:create_fody_schema.sql:14: ERROR:  relation "public.autonomous_system_annotation" does not exist
do-portal    | psql:create_fody_schema.sql:14: STATEMENT:  ALTER SEQUENCE fody.autonomous_system_annotation_autonomous_system_annotation_i_seq OWNED BY public.autonomous_system_annotation.autonomous_system_annotation_id;
```

**Comment by wagner-certat** [comment]
All `public.` needs to be replaced by `fody.`. I did that, but forgot that this can be necessary two times per line - I didn't use the g-Flag of sed.

I uploaded a new version of the file, but you can just apply the replacement yourself too.

**Comment by davewood** [comment]
https://github.com/certat/do-portal/commit/5143248f0ef150d29468c00f4088650c74de7b5a

**Comment by davewood** [comment]
@wagner-certat, @MarkHofstetter :  which tables do I need to fill for that?
