### ISSUE TITLE
Contacts: Use full browser window

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#67]
Please make it so that /#!/user_list uses all the available space in the browser window.

**Comment by davewood** [comment]
https://github.com/certat/customer-portal/commit/0e3c3bfbbf3da6bbf351dd8f6e6d02edb770d048

**Comment by certrik** [comment]
Nearly correct. Now the whole table is diplayed at once. But what is needed is that browser window is filled without the need for scrolling. Scrolling within the table is fine.

**Comment by davewood** [comment]
why is that needed? increasing the table dynamically is tricky enough as it is, pulling in more dependencies (screen size) will make the code even more un-maintainable. not to mention the mental gymnastics required to pull it off in the first place.

**Comment by certrik** [comment]
Well okay. Than please just make the table a bit larger that it better fits the browser window. It just felt to small in the original. Having the whole table loaded at once, like now, is just too slow.

**Comment by davewood** [comment]
larger? you mean the width? that's a fixed width of the layout inherited by the certeu project. Do you want the entire page to be wider?

**Comment by davewood** [comment]
http://bootstrapdocs.com/v3.2.0/docs/css/#grid-options

**Comment by davewood** [comment]
max table height set to 600px: commit -> git: 5a3dde7
