### ISSUE TITLE
Add link for "Download Events"

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#69]
Please add link for "Download events" in frontend. 
![Download_events](https://user-images.githubusercontent.com/42176839/54589045-dd161200-4a24-11e9-9754-fd3cc75d1916.png)
Functionality will be somehow done via reverse proxy. But still have to define that.

**Comment by davewood** [comment]
* f423054 - (HEAD -> topic-grafana, origin/topic-grafana) add Download events link (14 seconds ago) <David Schmidt>
