### ISSUE TITLE
email from newly created contacts not shown in organisation view anymore

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#70]
email adress from new created contacts is not shown anymore. See /#!/organizations/5 first four contacts in orga.
![grafik](https://user-images.githubusercontent.com/42176839/54765122-3d5dad00-4bf9-11e9-8333-a2fef09023d2.png)

**Comment by davewood** [comment]
Error also on my test system.

staging server backend and frontend are up to date.

data exists in DB but the ajax req returns empty attributes for some reason.

{"email": null, "id": 5754, "membership_role_id": 25, "mobile": null, "organization_id": 2, "phone": null, "sms_alerting": 0, "user_id": 499}

mark is looking into it.

**Comment by MarkHofstetter** [comment]
after some pondering this seems to be a frontend or rather a non-issue

the api returns all the data for the user - the data displayed (correctly) is the role/membership details data, which needs not to be filled in. So if the email/phone/etc is for the membership is present it is displayed
