### ISSUE TITLE
Eventdownload

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#73]
Procedure:

- [x] Script on the database server run every night
  - [x]  Queries all organization IDs from the backend
  - [x]  For every organization all netobjects are queried
  - [x]  For all these netobjects, the data for the past 7 days is retrieved from the DB and saved into files per organization
  - [x]   pushes the files to the backend server, directory to be defined
- [x]  The frontend provides a URL to download the events per organization
- [x]  The backend checks authorization and sends the file if allowed

@MarkHofstetter Please provide the name of the directory the files should be

**Comment by MarkHofstetter** [comment]
app/static/data 

(should be in .gitignore)

**Comment by MarkHofstetter** [comment]
added 79fd24f26b4c83039c9be2a538e6124b8726d0d3

curl -s -H "Content-Type: application/json" -H "Accept: application/json" -H "API-Authorization: <api-key>" http://localhost:8000/cp/1.0/organizations/<org_id>/download_events

needs 2 new config params

DATA_DIR="data"   # must be placed under app/static/
DATA_SUFFIX="json.zip"

so files must be named <org_id>.json.zip eg 4711.json.zip

**Comment by davewood** [comment]
Without a Content-Disposition header from the backend I cannot easily control the filename of the download file because the attribute download="events.json.zip" will be ignored if the same-origin policy is violated.

**Comment by davewood** [comment]
https://www.programcreek.com/python/example/58917/flask.send_file

**Comment by davewood** [comment]
http://flask.pocoo.org/docs/0.12/api/#flask.send_file

**Comment by wagner-certat** [comment]
It works.

The filename is still `download_events`.

**Comment by wagner-certat** [comment]
Created #77 for minor issues/feature requests
