### ISSUE TITLE
Remove copyright information and version in footer

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#74]
Is "© 2015-2016 CERT-EU v0.6.5" (/#!/login) at the moment. Please remove completely for the moment.

**Comment by davewood** [comment]
no can do
https://github.com/certeu/do-portal/blob/master/LICENSE

**Comment by certrik** [comment]
Oh didn't see that. Please make it "© 2015-2016 CERT-EU, © 2017-2019 CERT.at v0.6.5" .

**Comment by MarkHofstetter** [comment]
why v0.6.5?

**Comment by certrik** [comment]
Copyright issue is still investigated. Version ... I don't really mind as long as it is lesser than 1 at the moment.

**Comment by certrik** [comment]
Remove copyright info from login screen. Exchange copyright info on other sites with a link "About" which links to a static site where all relevant information will be displayed. Add just "CERT.at based on code © 2015-2016 CERT-EU" for now.

**Comment by davewood** [comment]
copyright info is part of the template wrapper, removing it from login screen means removing it from all pages.

**Comment by certrik** [comment]
then just exchange the text with the link, please.

**Comment by davewood** [comment]
done and available on stg

**Comment by davewood** [comment]
good catch

* e76c977 - (HEAD -> topic-grafana, origin/topic-grafana) show header view only if username is set (25 seconds ago) <David Schmidt>
