### ISSUE TITLE
/ripe/contact/ API endpoint needs IP address support

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#76]
currently only supports CIDRs

Works: https://cp-aec-stg.cert.at/api/1.0/ripe/contact?cidr=83.136.39.0/24
Does not work:
 * https://cp-aec-stg.cert.at/api/1.0/ripe/contact?cidr=83.136.39.1
 * https://cp-aec-stg.cert.at/api/1.0/ripe/contact?cidr=83.136.39.1/32

**Comment by MarkHofstetter** [comment]
using the correct pg cidr operator surprisingly fixes this issue

provided examples work now

**Comment by wagner-certat** [comment]
Thanks, it works
