### ISSUE TITLE
Incompatibility with current flask-login

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#8]
With a current version of flask-login:

```
AttributeError: 'LoginManager' object has no attribute 'token_loader'
```

See https://github.com/maxcountryman/flask-login/blob/594e5d77c1101a103c76caf46895cea350e14287/CHANGES#L13-L16

**Comment by MarkHofstetter** [comment]
how should the user/session handling behave?
+ automatic logout on browser close?
+ automatic logout if other (admin) sessions changes password?

**Comment by certrik** [comment]
I would say there has to be an idle timeout (15 min.) (show warning in frontend if 1 min remains), an absolute timeout (4 h) and close browser logout.

**Comment by MarkHofstetter** [comment]
absolute timeout is easy to configure
REMEMBER_COOKIE_DURATION=timedelta(hours=2)

idle timeout would require some work - is it worth it?
logout on browser close is easy and resolves this issue

**Comment by MarkHofstetter** [comment]
works now with most recent (2 years old!) version of flask-login
