### ISSUE TITLE
remove redirect from activate-account to login if password is not conform

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#89]
The activate-account redirects to the login if the entered password is not conform with the password policy. Please remove this redirect so the users stays on the password reset page.

**Comment by davewood** [comment]
https://github.com/certat/do-portal/blob/master/frontend/app/scripts/services/auth.js#L52

do you want the redirect removed entirely?

**Comment by certrik** [comment]
I think @wagner-certat meant to not redirect users which entered a password which doesn't comply with the password rules. If the password complies with the rule the user should be redirected.

**Comment by davewood** [comment]
this is the cause of the redirect.
https://github.com/certat/do-portal/blob/devel/frontend/app/scripts/services/authinterceptor.js#L39

if the backend doesnt respond with HTTP 401 in case of password policy errors everything should be fine.

**Comment by davewood** [comment]
fixed:

* f68b60e - (HEAD -> devel, origin/devel) send HTTP 400 if password violates policy (14 seconds ago) <David Schmidt>
