### ISSUE TITLE
Handling of duplicate mail addresses across organizations

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#97]
Currently it is forbidden to create multiple users with the same email address. But this may lead to a problem. Imagine two unrelated organizations 1 and 2 with the admins A and B.

A creates a user/contact under 1 with test@example.com. As test@example.com is also active at 2, B does the same and receives an error message. B can't create the user and also can't see the existing user of test@example.com, as the user is only visible in 1

**Comment by certrik** [comment]
Still to decide how wo solve this.

**Comment by MarkHofstetter** [comment]
the use case seems rather far fetched imho. At the moment the email is also the login name so it has to be unique

**Comment by wagner-certat** [comment]
> the use case seems rather far fetched imho. At the moment the email is also the login name so it has to be unique

Not all contacts are users. And some people are part of multiple organizations.

**Comment by certrik** [comment]
Can we somehow just link the already existing contact/user to the new organisation.

**Comment by MarkHofstetter** [comment]
that's already possible but only for an "upstream" admin

**Comment by certrik** [comment]
Error message shows password in plaintext
![grafik](https://user-images.githubusercontent.com/42176839/77359332-b1bab700-6d4b-11ea-97a6-f03cd586694a.png)

**Comment by MarkHofstetter** [comment]
> Error message shows password in plaintext
> ![grafik](https://user-images.githubusercontent.com/42176839/77359332-b1bab700-6d4b-11ea-97a6-f03cd586694a.png)

removed, was debugging

**Comment by MarkHofstetter** [comment]
works in principle, the only the problem remaining is that an alias user has to be created as another user before being changed to the correct role
