### ISSUE TITLE
Organizations shown twice for unnecessary "Organisation Administrator" roles

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#99]
For user 13, the organizations page looks like this:

 * Organization Full Name 16
   * Organization Full Name 17
   * Organization Full Name 17
   * testdt
 * Organization Full Name 37

Organization 17 is listed twice. The memberships of user 13 are these:

- Organization Full Name 16 (AEC SMS Alarmierung)
- Organization Full Name 16 (Single Point of Contact (SPoC))
- Organization Full Name 16 (24/7)
- Organization Full Name 16 (Ansprechpartner Primaer)
- Organization Full Name 17 (Administrator Organisation)
- Organization Full Name 16 (Administrator Organisation)
- Organization Full Name 37 (Administrator Organisation) 

The role "Organization Full Name 17 (Administrator Organisation)" may be the culprit here, as the user is allowed to see this organization anyway.

This bug may be a result of the fix for #91 (but the users can now see them)

I guess it is a backend issue, as the org is sent twice. If not, please reassign.

**Comment by MarkHofstetter** [comment]
tried but cannot reproduce: what steps have to be taken to come to this result?

**Comment by wagner-certat** [comment]
> tried but cannot reproduce: what steps have to be taken to come to this result?

As described above. User and Org ids are those on staging server

**Comment by wagner-certat** [comment]
![image](https://user-images.githubusercontent.com/25031221/75552226-255ff180-5a36-11ea-8a1b-6db8a572ebbd.png)

**Comment by MarkHofstetter** [comment]
I see the current situation but I am not able to reproduce it - please provide the steps to reproduce

**Comment by wagner-certat** [comment]
To reproduce:
* Create a new user or re-use an existing
* Set the user as Org Admin for any organisation
* Set the user as Org Admin for any sub-organsiation of the previous one

Just re-reproduced again on staging with user 527 and orgs 16 (parent) & 5075 (sub).

**Comment by MarkHofstetter** [comment]
tried it on most recent devel, cannot reproduce (maybe was resolved with some other bug) please try to reproduce on test instance - what I found that it is possible to create a membership twice which is a bug

**Comment by wagner-certat** [comment]
Works as intended on testing, thanks.
